* Name  = Kale Aniket Devidas
* TensorFlow Classification Problem
* Deep Learning 

In [7]:
# First programe of Tensorflow
import tensorflow as tf
hello = tf.constant("Hello Tensorflow!")
sess = tf.Session()
print(sess.run(hello))

b'Hello Tensorflow!'


In [3]:
# we will start Tensor flow Classification Problem.

* This notebook is a companion of A Visual and Interactive Guide to the Basics of Neural Networks.

* We are working on the classification Problem using Tensorflow
* We have two X columns Are of house and Number of Bathrooms
* We have to help to choose house from given datasets.

In [9]:
# Loading Important Lib
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline
import numpy as np

In [70]:
data = pd.read_csv("data.csv")
data.head()

index    area  bathrooms     price    sq_price
0      0  2104.0        3.0  399900.0  190.066540
1      1  1600.0        3.0  329900.0  206.187500
2      2  2400.0        3.0  369000.0  153.750000
3      3  1416.0        2.0  232000.0  163.841808
4      4  3000.0        4.0  539900.0  179.966667

In [71]:
# Shape of data
data.shape

(47, 5)

In [72]:
# Remove columns we dont care about
data.drop(["index", "price", "sq_price"], axis=1, inplace= True)

In [80]:
data = data.loc[0:9]
data.head(9)

area  bathrooms  y1
0  2104.0        3.0   1
1  1600.0        3.0   1
2  2400.0        3.0   1
3  1416.0        2.0   0
4  3000.0        4.0   0
5  1985.0        4.0   1
6  1534.0        3.0   0
7  1427.0        3.0   1
8  1380.0        3.0   1

In [81]:
 data.loc[:,("y1")] = [1, 1, 1, 0, 0, 1, 0, 1, 1, 1]

/Users/Aniket/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:476: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [82]:
data

area  bathrooms  y1
0  2104.0        3.0   1
1  1600.0        3.0   1
2  2400.0        3.0   1
3  1416.0        2.0   0
4  3000.0        4.0   0
5  1985.0        4.0   1
6  1534.0        3.0   0
7  1427.0        3.0   1
8  1380.0        3.0   1
9  1494.0        3.0   1

In [84]:
data.loc[:, ("y2")] = data["y1"] == 0 

/Users/Aniket/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/Users/Aniket/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:476: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [90]:
data.loc[:,("y2")] = data.y2.astype(int)

/Users/Aniket/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:476: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [91]:
# So our data is ready Now and we will build the Tensorflow on this data.

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [94]:
# Lets first we will convert our dataframes into the Matrix.
InputX = data.loc[:,("area", "bathrooms")].as_matrix()
InputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [96]:
InputY = data.loc[:,("y1", "y2")].as_matrix()
InputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

* Lets Prepare some Parameters to Train our Module.

In [97]:
# parameters
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_sample = InputY.size

* Declaration step of Tensorflow.
* We will Feed the input matrix to tensors and predict the weight and biases.

In [123]:
# feed the input with 2*2 matrix, area and bathrooms
x = tf.placeholder(tf.float32, [None,2])
# Now we have define the Weight
W = tf.Variable(tf.zeros([2,2]))
# create Biases also
b = tf.Variable(tf.zeros([2]))
# Prediction y = wx+b
y_values = tf.add(tf.matmul(x,W),b)

In [139]:
# we will define the Softmax function. output of softmax will be in Probability form.
y = tf.nn.softmax(y_values)

In [138]:
# output
y_ = tf.placeholder(tf.float32, [None,2])

* Now we have to calculate the cost function 

In [142]:
# cost function means MSE mean square error
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_sample)
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)
optimizer

In [146]:
# Intialize the all tensors 
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [168]:
for i in range(training_epochs):
    sess.run(optimizer, feed_dict = {x:InputX, y_: InputY})
    
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict = {x:InputX, y_: InputY})
        

In [169]:
print ("Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc))

Training step: 1999 cost= 0.109526418


In [167]:
print ("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: InputX, y_: InputY})
print ("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')

Optimization Finished!
Training cost= 0.109529 W= [[ 0.00021384 -0.00021384]
 [ 0.00020404 -0.00020404]] b= [  4.73109685e-05  -4.73109794e-05] 



In [172]:
# Prediction of anothe Feed
sess.run(y, feed_dict={x: InputX })

array([[ 0.71116656,  0.28883338],
       [ 0.66498935,  0.33501059],
       [ 0.73644829,  0.26355171],
       [ 0.64712906,  0.35287091],
       [ 0.78322923,  0.21677083],
       [ 0.70071334,  0.29928669],
       [ 0.65867507,  0.34132493],
       [ 0.64831835,  0.35168162],
       [ 0.64372396,  0.35627601],
       [ 0.6548205 ,  0.34517956]], dtype=float32)